Rework Getting Started/projects page
c3lang/c3-web pull request #54
Opened 2024-10-02 08:09 UTC by tomaskallup

I had to change `projects.md` to `projects.mdx` and update astro (I did so via the recommended `npx @astrojs/upgrade`), which changed some type files inside `.astro`, to allow usage of their custom `<FileTree>` component, which renders a nice clickable file tree.

Other then that, I tried to make `projects.mdx` more of a "copy" of the Hello world, to make sure it includes information about building & running.

2024-10-02 19:53 UTC, joshring requested changes

2024-10-02 19:53 UTC, joshring commented on src/content/docs/Getting Started/projects.mdx
> +They also allow you so specify libraries to link and define how your project should be built for specific targets.
```suggestion
They also allow you to specify libraries to link, and define how your project should be built for specific targets.
```

2024-10-02 19:53 UTC, joshring commented on src/content/docs/Getting Started/projects.mdx
> +- `README.md` file where you can describe your project
```suggestion
#### Directory Overview

| Directory       | Usage         |
|-----------------|---------------|
| `./build`       | Where your temporary files and build results will go. |
| `./docs`        | Code Documentation |
| `./lib`         | C3 libraries (with the .c3l suffix) |
| `./resources`   | Non-code esources like images, sound effects etc. |
| `./scripts`     | Scripts, including .c3 scripts that generate code at compile time. |
| `./src`         | Storing our code, by default contains `main.c3` with "Hello World". |
| `project.json`  | Record project information, similar to `package.json` in NodeJS. |
| `LICENSE`       | Project license. |
| `README.md`     | Help others understand and use your code. | 
```

2024-10-02 19:53 UTC, joshring commented on src/content/docs/Getting Started/projects.mdx
> +```
```suggestion
:::Note
If you want to build a specific target, you can do so by specifying its name.
The default target is created with the name of the project, such as `myc3project`.

```bash 
c3c build myc3project
```
:::
```

2024-10-02 19:53 UTC, joshring commented on src/content/docs/Getting Started/projects.mdx
> +We can simply build it with:
Let's move the c3c run part so it's first before `c3c build`, so they can see the most important information first

2024-10-02 19:53 UTC, joshring commented on src/content/docs/Getting Started/projects.mdx
> +### 🏃 Building and running
See above note about moving this section before the `c3c build`

2024-10-02 19:54 UTC, joshring commented
Thanks it's quite a nifty new feature

It got me thinking about the page names, in addition to above

Shall we change `Hello World in C3` to `Hello World` then it seems more consistent with `Projects`? Or if you have some better titles let's see what you have

I noticed we have Svelte installed but we're not using it, could we nuke that with:
`npm uninstall @astrojs/svelte`

2024-10-02 20:37 UTC, tomaskallup commented
I thought about renaming the Hello World to something like `Standalone Compilation`, but I feel like Hello World is so easily recognizable, it's a better name, since it gives you a starting point.

Making it simply `Hello World` is a good idea, there is no need for the suffix.

2024-10-02 20:44 UTC, joshring commented on src/content/docs/Getting Started/projects.mdx
> +```
I think the ::: got a bit lost here, but hopefully you know what I meant

2024-10-03 10:41 UTC, joshring approved these changes

2024-10-03 10:54 UTC, tomaskallup commented
Accidentaly clicked on the request review, my page was outdated and I didn't see the approve, sorry for that!

2024-10-03 11:13 UTC, merged

2024-10-03 11:13 UTC, lerno commented
Thank you!