Added segment about string types and their corresponding member functions
c3lang/c3-web pull request #87
Opened 2024-11-14 19:14 UTC by Nizarll

i think this segment was pretty important especially since the programming language targets people from a c background so providing an explanation of the underlying implementations .

2024-11-14 19:16 UTC, Nizarll commented
However i'm thinking about making a different segment for member functions of most of the underlying types something similar to cppreference where any type from the standard library or the base types that states all of their member functions shows examples and usage

2024-11-15 15:45 UTC, joshring commented
> However i'm thinking about making a different segment for member functions of most of the underlying types something similar to cppreference where any type from the standard library or the base types that states all of their member functions shows examples and usage

A separate section might be good (second PR?), people have also asked about the mathematical operations defined as member functions too.

2024-11-15 16:00 UTC, joshring requested changes
Thanks for this!
Some small bits, added some suggestions to speed things along :+1:

2024-11-15 16:00 UTC, joshring commented on src/content/docs/Language Common/strings.md
> +A ZString is a distinct type for null-terminated C-style strings ` char* `. Converting a ` char* ` to a ` ZString ` requires an explicit cast to ensure the safety and `\0` termination of the string d
Perhaps we can add the use-case of this string type:

```suggestion
ZString is used when working with C code, which expects null-terminated C-style strings of type `char*`. it is a distinct type so converting to a `ZString` requires an explicit cast. This helps to remind the user to check there is appropriate `\0` termination of the string data.
```

2024-11-15 16:00 UTC, joshring commented on src/content/docs/Language Common/strings.md
> +Strings are usually the typical type to use, they can be sliced , compared etc ... \
Strings are the typical string type to use, they can be sliced, compared, split etc, [the string methods are outlined here](#string-member-functions).
It is possible to access the length of a `String` instance through the  `.len`  member, eg
```c3
String my_string = "example";
int length = my_string.len
```

2024-11-15 16:00 UTC, joshring commented on src/content/docs/Language Common/strings.md
> +#### ZString :
So we can link directly to this heading (H3 is linkable, H4 is not)
```suggestion
### ZString Member Functions
```

2024-11-15 16:00 UTC, joshring commented on src/content/docs/Language Common/strings.md
> +#### String :
So we can link directly to this heading (H3 is linkable, H4 is not)
```suggestion
### String Member Functions
```

2024-11-15 17:30 UTC, Nizarll commented
> > However i'm thinking about making a different segment for member functions of most of the underlying types something similar to cppreference where any type from the standard library or the base types that states all of their member functions shows examples and usage
> 
> A separate section might be good (second PR?), people have also asked about the mathematical operations defined as member functions too.

i think the first part without the member functions should be kept , but the member functions should probably be in a whole other **Section** about the standard library's type and the functions as well as examples similar to cppref i will be preparing a second pr this week ! I am still wondering about the name of the section though

2024-11-15 21:56 UTC, joshring commented
What jumps to mind immediately is "Type Member Functions"

2024-11-18 20:24 UTC, joshring requested changes

2024-11-18 20:24 UTC, joshring commented on src/content/docs/Language Common/strings.md
> +#### ZString
```suggestion
### ZString
```
so we can link, H3 is linkable

2024-11-18 20:24 UTC, joshring commented on src/content/docs/Language Common/strings.md
> +>  **⚠️**  Converting a `String` to a `ZString` should be done carefully to ensure \0 termination of the underlying `char*`.
```suggestion
:::caution  
Ensure the terminal `\0` when converting from `String` to `ZString`.
:::
```

2024-11-18 20:24 UTC, joshring commented on src/content/docs/Language Common/strings.md
> +#### String
```suggestion
### String
```
H3 is linkable

2024-11-19 20:45 UTC, joshring commented
Thanks @Nizarll could you apply those above? then we can look to get this merged :)

2024-11-20 07:04 UTC, Nizarll commented
Alright , done.
I've been preparing the pr for default types member functions it should be done in a few days !

2024-11-22 12:10 UTC, joshring commented
Still a few suggestions left, but nearly there

2024-11-25 23:31 UTC, lerno commented
Is this ok now @joshring

2024-11-26 00:25 UTC, joshring approved these changes

2024-11-26 00:26 UTC, joshring commented
Thanks!, all good

2024-11-26 00:31 UTC, merged

2024-11-26 00:31 UTC, lerno commented
Thank you for the hard work!