Added examples for some parts of the standard library
c3lang/c3-web pull request #88
Opened 2024-11-17 15:33 UTC by cavetownie

#### Simple examples added
* Fixed typo for deprecated `is_comparable` to `is_comparable_value`
* Examples for printf
* Examples for treadline
* Examples for readline

2024-11-18 20:55 UTC, joshring requested changes
Thanks :) some small bit with suggestions to speed things along

2024-11-18 20:55 UTC, joshring commented on src/content/docs/Standard Library/index.mdx
> +Read a `String!` from a file stream. Defaults to standard input (stdin). Reads to the next newline or to the end of stream. `Readline` returns an optional, and must be handled accordingly.
```suggestion
Read a `String!` from a file stream, which is standard input (stdin) by default, reads to the next newline character `\n` or to the end of stream. `Readline` returns an [Optional](/language-common/optionals-essential/#what-is-an-optional) string.
```

2024-11-18 20:55 UTC, joshring commented on src/content/docs/Standard Library/index.mdx
> +```
```suggestion
```c3
import std::io;

fn void! main() 
{
    String! name = io::readline();
    if (catch excuse = name) 
    {
        return excuse?;
    }

    io::printfn("Name was: %s.", name);
}
```
```

trying to minimise line length as much as possible (so it works nicely on mobile screens) and newlines for `{` as per the style we've got for the rest of the guide

2024-11-18 20:55 UTC, joshring commented on src/content/docs/Standard Library/index.mdx
> +Read a `String!` from a file stream. Defaults to standard input (stdin). Reads to the next newline or to the end of stream. `Treadline` returns an optional, and must be handled accordingly. Additiona
```suggestion
Read a `String!` from a file stream which is standard input (stdin) by default, Reads to the next newline character `\n` or to the end of stream. `Treadline` returns an [Optional](/language-common/optionals-essential/#what-is-an-optional) string. The temporary allocator is used by `Treadline`, in contrast the `readline` defaults to the heap allocator, but is configurable to other allocators. 
```

2024-11-18 20:55 UTC, joshring commented on src/content/docs/Standard Library/index.mdx
> +}
```suggestion
```c3
import std::io;

fn void! main() 
{
    String! name = io::treadline();
    if (catch excuse = name) 
    {
        return excuse?;
    }

    io::printfn("Hello %s! Hope you have a great day", name);
}
```

2024-11-18 20:55 UTC, joshring commented on src/content/docs/Standard Library/index.mdx
> +`\r` will be filtered from the String.
```suggestion
:::Note
`\r` will be filtered from the String.
:::
```

2024-11-18 20:55 UTC, joshring commented on src/content/docs/Standard Library/index.mdx
> +```
```suggestion
### void print(x), void printn(x = "")

Print a value to stdout works for the majority of types, including structs, which can be helpful for debugging.
The `printn` variant appends a newline.

```c3
import std::io;

enum Heat 
{
    WARM,
    WARMER,
    REALLY_WARM,
}

fn void main() 
{
    int[<2>] vec = { 4, 2 };
    Heat weather = WARM;
    int[5] fib = { 0, 1, 1, 2, 3 };
    String dialogue = "secret";

    io::print("Hello");   // Hello
    io::print(20);        // 20
    io::print(2.2);       // 2.200000
    io::print(vec);       // [<4, 2>]
    io::print(weather);   // WARM
    io::print(fib);       // [0, 1, 1, 2, 3] 
    io::print(dialogue);  // secret
}
```
```
docs style is `{` on newline, Line length optimised, using `//` style comments

2024-11-18 20:55 UTC, joshring commented on src/content/docs/Standard Library/index.mdx
> +```
```suggestion
```c3
import std::io;

enum Heat 
{
    WARM,
    WARMER,
    REALLY_WARM,
}

fn void main() 
{
    int[<2>] vec = { 4, 2 };
    Heat weather = REALLY_WARM;
    String dialogue = "Hello";

    io::printfn("%s", dialogue);  // Hello
    io::printfn("%d", 20);        // 20
    io::printfn("%f", 2.2);       // 2.200000
    io::printfn("%s", vec);       // [<4, 2>]
    io::printfn("%s", weather);   // REALLY_WARM
}
```
```

2024-11-19 08:06 UTC, cavetownie commented
@joshring I think that should be it then? :) Do let me know otherwise!

2024-11-19 09:27 UTC, joshring commented on src/content/docs/Standard Library/index.mdx
>  `\r` will be filtered from the String.
```suggestion
:::Note
`\r` will be filtered from the String.
:::
```

2024-11-19 09:27 UTC, joshring commented
One small part I forgot, added a suggestion to speed along, then we're all green

2024-11-19 12:32 UTC, lerno commented
Is it all ok now @joshring

2024-11-19 12:58 UTC, joshring approved these changes

2024-11-19 23:13 UTC, merged

2024-11-19 23:13 UTC, lerno commented
Thank you!